### ISSUE TITLE
How to know proper size for XAML

### ISSUE THREAD

**Issue by ftballguy45** [ElinamLLC/SharpVectors-SvgXaml#1]
Hello,

Exploring the XAML export feature - very cool. How do we know a good size (programmatically) to use for example a Rectangle that has a Fill which is a DrawingBrush that contains the exported XAML DrawingGroup?

**Comment by paulushub** [comment]
@ftballguy45 You can only get the bounding rectangle when you load the XAML file and create the DrawingGroup object instance.
